List names = [
  "Hypertensive disease",
  "Coronavirus disease 2019",
  "Depression mental",
  "Depressive disorder",
  "Coronary arteriosclerosis",
  "Coronary heart disease",
  "Pneumonia",
  "Failure heart congestive",
  "Accident cerebrovascular",
  "Asthma",
  "Myocardial infarction",
  "Hypercholesterolemia",
  "Infection",
  "Infection urinary tract",
  "Anemia",
  "Chronic obstructive airway disease",
  "Dementia",
  "Insufficiency renal",
  "Confusion",
  "Degenerative polyarthritis",
  "Hypothyroidism",
  "Anxiety state",
  "Malignant neoplasms",
  "Primary malignant neoplasm",
  "Acquired immuno-deficiency syndrome",
  "Hiv",
  "Hiv infections",
  "Cellulitis",
  "Gastroesophageal reflux disease",
  "Septicemia",
  "Systemic infection",
  "Sepsis (invertebrate)",
  "Deep vein thrombosis",
  "Dehydration",
  "Neoplasm",
  "Embolism pulmonary",
  "Epilepsy",
  "Cardiomyopathy",
  "Chronic kidney failure",
  "Carcinoma",
  "Hepatitis c",
  "Peripheral vascular disease",
  "Psychotic disorder",
  "Hyperlipidemia",
  "Bipolar disorder",
  "Obesity",
  "Ischemia",
  "Cirrhosis",
  "Exanthema",
  "Benign prostatic hypertrophy",
  "Kidney failure acute",
  "Mitral valve insufficiency",
  "Arthritis",
  "Bronchitis",
  "Hemiparesis",
  "Osteoporosis",
  "Transient ischemic attack",
  "Adenocarcinoma",
  "Paranoia",
  "Pancreatitis",
  "Incontinence",
  "Paroxysmal dyspnea",
  "Hernia",
  "Malignant neoplasm of prostate",
  "Carcinoma prostate",
  "Edema pulmonary",
  "Lymphatic diseases",
  "Stenosis aortic valve",
  "Malignant neoplasm of breast",
  "Carcinoma breast",
  "Schizophrenia",
  "Diverticulitis",
  "Overload fluid",
  "Ulcer peptic",
  "Osteomyelitis",
  "Gastritis",
  "Bacteremia",
  "Failure kidney",
  "Sickle cell anemia",
  "Failure heart",
  "Upper respiratory infection",
  "Hepatitis",
  "Hypertension pulmonary",
  "Deglutition disorder",
  "Gout",
  "Thrombocytopaenia",
  "Hypoglycemia",
  "Pneumonia aspiration",
  "Colitis",
  "Diverticulosis",
  "Pneumocystis carinii pneumonia",
  "Hepatitis b",
  "Parkinson disease",
  "Lymphoma",
  "Hyperglycemia",
  "Encephalopathy",
  "Tricuspid valve insufficiency",
  "Alzheimer's disease",
  "Candidiasis",
  "Oralcandidiasis",
  "Neuropathy",
  "Kidney disease",
  "Fibroid tumor",
  "Glaucoma",
  "Neoplasm metastasis",
  "Malignant tumor of colon",
  "Carcinoma colon",
  "Ketoacidosis diabetic",
  "Tonic-clonic epilepsy",
  "Tonic-clonic seizures",
  "Respiratory failure",
  "Melanoma",
  "Gastroenteritis",
  "Malignant neoplasm of lung",
  "Carcinoma of lung",
  "Manic disorder",
  "Personality disorder",
  "Primary carcinoma of the liver cells",
  "Emphysema pulmonary",
  "Hemorrhoids",
  "Spasm bronchial",
  "Aphasia",
  "Obesity morbid",
  "Pyelonephritis",
  "Endocarditis",
  "Effusion pericardial",
  "Pericardial effusion body substance",
  "Chronic alcoholic intoxication",
  "Pneumothorax",
  "Delirium",
  "Neutropenia",
  "Hyperbilirubinemia",
  "Influenza",
  "Dependence",
  "Thrombus",
  "Cholecystitis",
  "Hernia hiatal",
  "Migraine disorders",
  "Pancytopenia",
  "Cholelithiasis",
  "Biliary calculus",
  "Tachycardia sinus",
  "Ileus",
  "Adhesion",
  "Delusion",
  "Affect labile",
  "Decubitus ulcer",
];
